const state={readiness:{current:100},activeScenario:"IDLE",activeTheme:"redline"};
const themeEngine={apply(t){document.documentElement.setAttribute("data-theme",t);state.activeTheme=t;saveState();soundEngine.auto();applyThemeFilter(t)},auto(){const r=state.readiness.current||100;const h=new Date().getHours();const s=state.activeScenario;if(h<6||h>22)return this.apply("nightops");if(r>=80||s==="HIGH_CAPACITY")return this.apply("redline");if(r<40||s==="LOW_CAPACITY")return this.apply("stealth");return this.apply("overclock")}};
const soundEngine={current:null,play(id){if(this.current===id)return;["sndNightOps","sndRedline","sndStealth","sndOverclock"].forEach(x=>{const e=document.getElementById(x);if(e)e.pause()});const el=document.getElementById(id);if(!el)return;el.currentTime=0;el.volume=.18;el.play().catch(()=>{});this.current=id},auto(){const t=state.activeTheme;if(t==="nightops")return this.play("sndNightOps");if(t==="redline")return this.play("sndRedline");if(t==="stealth")return this.play("sndStealth");if(t==="overclock")return this.play("sndOverclock")}};
function applyThemeFilter(t){const el=document.getElementById(soundEngine.current);if(!el)return;if(!el._ctx){el._ctx=new (window.AudioContext||window.webkitAudioContext)();el._source=el._ctx.createMediaElementSource(el);el._filter=el._ctx.createBiquadFilter();el._source.connect(el._filter).connect(el._ctx.destination)}const f=el._filter;if(t==="nightops"){f.type="lowpass";f.frequency.value=600}else if(t==="redline"){f.type="highpass";f.frequency.value=1200}else if(t==="stealth"){f.type="lowpass";f.frequency.value=300}else if(t==="overclock"){f.type="peaking";f.frequency.value=2000;f.gain.value=4}}
function saveState(){try{localStorage.setItem("beyondState",JSON.stringify(state))}catch(e){}}
function loadState(){try{const s=localStorage.getItem("beyondState");if(!s)return;Object.assign(state,JSON.parse(s))}catch(e){}}
function toneUp(){const a=document.getElementById("sndToneUp");if(a){a.currentTime=0;a.play().catch(()=>{})}}
function toneDown(){const a=document.getElementById("sndToneDown");if(a){a.currentTime=0;a.play().catch(()=>{})}}
function playScenarioStinger(){const a=document.getElementById("sndScenario");if(a){a.currentTime=0;a.play().catch(()=>{})}}
function playSpatial(id,x){const el=document.getElementById(id);if(!el)return;const pan=(x/window.innerWidth)*2-1;const ctx=new (window.AudioContext||window.webkitAudioContext)();const src=ctx.createMediaElementSource(el);const p=ctx.createStereoPanner();p.pan.value=pan;src.connect(p).connect(ctx.destination);el.currentTime=0;el.play().catch(()=>{})}
function playEcho(id,x){playSpatial(id,x);setTimeout(()=>playSpatial(id,x+40),90);setTimeout(()=>playSpatial(id,x-40),180)}
const subsystemAnchors={workout:.2,meals:0,grocery:.8};
function playSubsystemCue(id,s){const x=subsystemAnchors[s]*window.innerWidth;playSpatial(id,x)}
function computeReadiness(){state.readiness.current=Math.max(10,Math.min(100,state.readiness.current));document.getElementById("readinessValue").textContent=state.readiness.current}
function setScenario(s){state.activeScenario=s;document.getElementById("scenarioValue").textContent=s;playScenarioStinger();themeEngine.auto();saveState()}
function spawnParticles(){const c=document.getElementById("hudParticles");for(let i=0;i<40;i++){const p=document.createElement("div");p.className="particle";p.style.left=Math.random()*100+"vw";p.style.top=Math.random()*100+"vh";p.style.animationDuration=8+Math.random()*10+"s";c.appendChild(p)}}
function spawnHUDObjects(){const c=document.getElementById("hudObjects");for(let i=0;i<4;i++){const o=document.createElement("div");o.className="hud-object";o.style.left=Math.random()*100+"vw";o.style.top=Math.random()*100+"vh";o.style.animationDuration=15+Math.random()*20+"s";c.appendChild(o)}}
let hoverTimer=null;
function initHover(){document.querySelectorAll(".panel").forEach(p=>{p.addEventListener("mouseenter",()=>{hoverTimer=setTimeout(()=>p.classList.add("panel-hover-activated"),450)});p.addEventListener("mouseleave",()=>{clearTimeout(hoverTimer);p.classList.remove("panel-hover-activated")})})}
let lastX=0,lastY=0,lastTime=Date.now();
function initGestures(){document.addEventListener("mousemove",e=>{const now=Date.now();const dt=now-lastTime;const dx=e.clientX-lastX;const dy=e.clientY-lastY;const speed=Math.hypot(dx,dy)/dt;if(speed>1.2){if(Math.abs(dx)>Math.abs(dy)){if(dx>0)gesture("swipe-right");else gesture("swipe-left")}else{if(dy>0)gesture("swipe-down");else gesture("swipe-up")}}document.body.dataset.speed=speed>1.5?"fast":"slow";document.querySelectorAll(".panel").forEach(p=>{const r=p.getBoundingClientRect();const cx=r.left+r.width/2;const cy=r.top+r.height/2;const dist=Math.hypot(e.clientX-cx,e.clientY-cy);p.dataset.prox=dist<120?"near":"far";const dxp=(e.clientX-cx)*.01;const dyp=(e.clientY-cy)*.01;p.style.transform=`translate(${dxp}px,${dyp}px)`;const x=((e.clientX-r.left)/r.width)*100;const y=((e.clientY-r.top)/r.height)*100;p.style.setProperty("--px",x+"%");p.style.setProperty("--py",y+"%")});const amb=document.getElementById(soundEngine.current);if(amb){const cxw=window.innerWidth/2;const cyw=window.innerHeight/2;const dist=Math.hypot(e.clientX-cxw,e.clientY-cyw);const maxDist=Math.hypot(cxw,cyw);amb.volume=.12+(dist/maxDist)*.06}lastX=e.clientX;lastY=e.clientY;lastTime=now})}
function gesture(t){document.body.dataset.gesture=t;if(t==="swipe-left")navigateTo("today");if(t==="swipe-right")navigateTo("workout");if(t==="swipe-up")openQuickActions();if(t==="swipe-down")closeQuickActions()}
function navigateTo(m){toneUp()}
function openQuickActions(){toneUp()}
function closeQuickActions(){toneDown()}
function initThemeSwitcher(){document.querySelectorAll('#themeSwitcher button').forEach(b=>{b.addEventListener("click",()=>{themeEngine.apply(b.dataset.theme);toneUp()})})}
function bootSequence(){const b=document.getElementById("bootScreen");setTimeout(()=>{b.style.opacity=0;setTimeout(()=>b.style.display="none",600)},1200)}
function initNavButtons(){document.querySelectorAll(".nav-button[data-nav]").forEach(btn=>{btn.addEventListener("click",e=>{const t=btn.dataset.nav;playSpatial("sndToneUp",e.clientX);if(t==="workout")setScenario("HIGH_CAPACITY");if(t==="meals")setScenario("IDLE");if(t==="grocery")setScenario("LOW_CAPACITY")})})}
window.addEventListener("load",()=>{loadState();spawnParticles();spawnHUDObjects();initHover();initGestures();initThemeSwitcher();initNavButtons();computeReadiness();themeEngine.auto();bootSequence()});
